// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/10/2025, 14:00:40
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/plugins/**/*.{js,ts,mjs}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/composables/**/*.{js,ts,mjs}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/utils/**/*.{js,ts,mjs}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Proyecto_Cristal-main/Proyecto_Cristal-main/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;