// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/10/2025, 18:08:36
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/plugins/**/*.{js,ts,mjs}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/composables/**/*.{js,ts,mjs}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/utils/**/*.{js,ts,mjs}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/usuario/OneDrive/Desktop/Proyectos ESD/4º/Proyectos/Glass Lab/Web/Proyecto_Cristal/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;