// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/11/2025, 11:20:48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/plugins/**/*.{js,ts,mjs}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/composables/**/*.{js,ts,mjs}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/utils/**/*.{js,ts,mjs}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Antoño/Desktop/Glass_LAB/Proyecto_Cristal-Casi_todo/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;